create table users
(
    id           integer      generated by default as identity
        constraint users_pk
            primary key,
    first_name   varchar(255) not null,
    last_name    varchar(255) not null,
    email        varchar(255),
    password      varchar(255)
);

alter table users
    owner to student;

create unique index users_id_index
    on users (id);
