create table member
(
    id           integer      generated by default as identity
        constraint member_pk
            primary key,
    first_name   varchar(255) not null,
    last_name    varchar(255) not null,
    email        varchar(255),
    password      varchar(255)
);

alter table member
    owner to student;

create unique index member_id_index
    on member (id);