create table coach_topic
(
    id         integer generated by default as identity
        constraint coach_topic_pk
            primary key,
    topic_name varchar(255),
    experience_level  integer not null
);

alter table coach_topic
    owner to student;

create unique index coach_topic_id_index
    on coach_topic (id);
