create table coach
(
    id               integer generated by default as identity
        constraint coach_pk
            primary key,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    email      varchar(255),
    coach_topic       varchar(255),
    training_class varchar(255)
);

alter table coach
    owner to student;

create unique index coach_id_index
    on coach (id);
