pipeline {
    agent any
        tools {
            jdk 'jdk-15'
            maven 'Maven'
        }

    stages {

        stage('Config') {
            steps {
                sh 'sed -ri \'s/frederik/noobs-test/g\' ./src/main/resources/application.properties'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean test-compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn clean test'
            }
        }

    }

    post {
        always {
            junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml'
        }
    }
}
